#pragma once
#define comenzi "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Comenzi.txt"
#define recenzii "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Recenzii.txt"
#define stoc "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Stoc.txt"
#define stoc_aux "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Stoc_aux.txt"
#include "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Culori.h"
#include "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Produs.h"
#include "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Data.h"
#include "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Cos_cumparaturi.h"
#include "C:/Users/pasca/Desktop/Chestii C++/Proiect personal/Fisiere comune/Recenzie.h"